name: IntegratBuild Next.js aplication

on: push
jobs:
    build-project:
        name: Build project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install npm dependen
              run: npm install
            - name: Build prioject asset
              run: npm run build
            - name: Upload static site content
              uses: actions/upload-artifact@v4
              with:
                name: statis-site
                path: .next/
                include-hidden-files: true


